### ISSUE TITLE
Review Redeemer optimization trick

### ISSUE THREAD

**Issue by ignaciodopazo** [Vortecsmaster/EA_BuidlNOW_Crowdfunding#4]
https://github.com/Vortecsmaster/EA_BuidlNOW_Crowdfunding/blob/c217353aa0db6b08d86689d95dfa675da61debd8/crowdfunding_v02/validators/campaingmanagementv02.ak#L22
I'm aware that this optimization trick was very useful in Haskell on-chain lib but not sure about Aiken, maybe Aiken compiler is smart enough to perform it? 
I could make a quick & dirty test to see if makes sense for Aiken. I noted that in [Anastasia Labs design patterns](https://github.com/Anastasia-Labs/design-patterns) the optimization [is presented](https://github.com/Anastasia-Labs/design-patterns/blob/main/enum-redeemers/ENUM-REDEEMERS.md) but no mention of it in the [aiken design patters abstractions implementations from them](https://github.com/Anastasia-Labs/aiken-design-patterns). Because I think reducing information overhead throughout the course by trimming unnecessary things is important. In case this is desired for learning purposes, ignore it!

**Comment by Vortecsmaster** [comment]
Actually initially it was intended, but, as you said, an unnecesary complexity from PlutusTX, so i decided to go directly into optimized redeemers. Specially due to the beginners crowd, serializing data is complex enough already to bring unnecesary complexity at the first steps.
