### ISSUE TITLE
Campaign redeemer: `campaign_id` not needed 

### ISSUE THREAD

**Issue by ignaciodopazo** [Vortecsmaster/EA_BuidlNOW_Crowdfunding#5]
For campaign redeemer,
https://github.com/Vortecsmaster/EA_BuidlNOW_Crowdfunding/blob/c217353aa0db6b08d86689d95dfa675da61debd8/crowdfunding_v03/lib/crowdfunding_v03/types.ak#L23-L29
passing the `campaign_id`
https://github.com/Vortecsmaster/EA_BuidlNOW_Crowdfunding/blob/c217353aa0db6b08d86689d95dfa675da61debd8/crowdfunding_v03/lib/crowdfunding_v03/types.ak#L26
is not necessary. Since the id is already present in the datum, the only computation is to perform equality check against it, and if this check is not performed, I don't see any possible issues.

**Comment by Vortecsmaster** [comment]
That's on pourpose, im looking for learners to find specifics details that can be improved, modified or removed. They are informed of that little mental game. Not too complex, but at some point between versions should be mentioned.

**Comment by ignaciodopazo** [comment]
Agree!
